# Generated by Django 4.2.23 on 2026-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengguna/')),
                ('kode_pengguna', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nama_pengguna', models.CharField(max_length=150)),
                ('nim_nik', models.CharField(max_length=40, unique=True, verbose_name='NIM/NIK')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('no_hp', models.CharField(max_length=30, verbose_name='No HP')),
                ('alamat', models.TextField()),
                ('fakultas', models.CharField(max_length=120)),
                ('prodi', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('laki_laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'ordering': ['nama_pengguna'],
            },
        ),
    ]
