# Generated by Django 4.2.23 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('laboran', 'Laboran'), ('asisten_lab', 'Asisten Lab'), ('mahasiswa', 'Mahasiswa')], default='mahasiswa', max_length=30),
        ),
    ]
