# Generated by Django 4.2.23 on 2026-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_pengguna_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Terverifikasi'),
        ),
    ]
