# Generated by Django 4.2.23 on 2026-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_pengguna_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='notifikasi_dibaca_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
