# Generated by Django 4.2.23 on 2026-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_reset_master_akademik_fti'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pengguna/backgrounds/'),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='background_mode',
            field=models.CharField(choices=[('default', 'Default'), ('clean', 'Clean'), ('lab', 'Lab'), ('aurora', 'Aurora'), ('grid', 'Grid'), ('custom', 'Custom')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Terang'), ('dark', 'Gelap')], default='light', max_length=20),
        ),
    ]
