# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0008_pengguna_background_image_pengguna_background_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
