# Generated by Django 4.2.23 on 2026-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0009_alter_pengguna_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pengguna/cv/', verbose_name='CV'),
        ),
    ]
