# Generated by Django 4.2.23 on 2026-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0013_pengguna_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengalamanpengguna',
            name='file_sertifikat',
            field=models.FileField(blank=True, upload_to='pengguna/sertifikat/'),
        ),
        migrations.AddField(
            model_name='pengalamanpengguna',
            name='nomor_kredensial',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pengalamanpengguna',
            name='tautan',
            field=models.URLField(blank=True, verbose_name='Tautan'),
        ),
        migrations.AddField(
            model_name='pengalamanpengguna',
            name='teknologi',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
