# Generated by Django 4.2.23 on 2026-07-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0015_school_pengalaman_pendidikan_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='school',
            new_name='pengguna_sc_npsn_495644_idx',
            old_name='pengguna_sc_npsn_36628f_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='pengguna_sc_jenjang_400641_idx',
            old_name='pengguna_sc_jenjang_c50f29_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='pengguna_sc_provins_9c0bb4_idx',
            old_name='pengguna_sc_provins_1bbd39_idx',
        ),
    ]
