"""
Django settings for project_laboran project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import mimetypes
import os
from importlib.util import find_spec
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Python on some Windows installations maps ES modules to text/plain, which
# makes browsers reject the bundled PDF.js files.
mimetypes.add_type('text/javascript', '.mjs')


def env_path(name, default):
    value = Path(os.getenv(name, default)).expanduser()
    return value if value.is_absolute() else BASE_DIR / value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me'
    else:
        raise ImproperlyConfigured('SECRET_KEY wajib diatur saat DEBUG=False.')

if not DEBUG and (
    len(SECRET_KEY) < 50
    or SECRET_KEY.startswith(('django-insecure', 'change-me', 'replace-with'))
):
    raise ImproperlyConfigured(
        'SECRET_KEY production harus acak, unik, dan minimal 50 karakter.'
    )

LABHUB_LICENSE_ENFORCED = os.getenv('LABHUB_LICENSE_ENFORCED', 'False') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

PUBLIC_ACCESS_BASE_URL = os.getenv('PUBLIC_ACCESS_BASE_URL', 'http://127.0.0.1:8000')
URL_PREFIX = os.getenv('FORCE_SCRIPT_NAME', '').strip().rstrip('/')
FORCE_SCRIPT_NAME = URL_PREFIX or None
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'
LOGIN_MAX_ATTEMPTS = int(os.getenv('LOGIN_MAX_ATTEMPTS', '5'))
LOGIN_LOCKOUT_SECONDS = int(os.getenv('LOGIN_LOCKOUT_SECONDS', '900'))
PASSWORD_RESET_MAX_REQUESTS = int(os.getenv('PASSWORD_RESET_MAX_REQUESTS', '3'))
PASSWORD_RESET_WINDOW_SECONDS = int(os.getenv('PASSWORD_RESET_WINDOW_SECONDS', '900'))
OTP_RESEND_MAX_REQUESTS = int(os.getenv('OTP_RESEND_MAX_REQUESTS', '3'))
OTP_RESEND_WINDOW_SECONDS = int(os.getenv('OTP_RESEND_WINDOW_SECONDS', '900'))
PROFILE_PHOTO_MAX_BYTES = int(os.getenv('PROFILE_PHOTO_MAX_BYTES', str(5 * 1024 * 1024)))
PROFILE_PHOTO_MAX_PIXELS = int(os.getenv('PROFILE_PHOTO_MAX_PIXELS', '20000000'))

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '').strip()
OPENAI_CHATBOT_MODEL = os.getenv('OPENAI_CHATBOT_MODEL', 'gpt-4o-mini').strip() or 'gpt-4o-mini'
OPENAI_CHATBOT_TIMEOUT_SECONDS = int(os.getenv('OPENAI_CHATBOT_TIMEOUT_SECONDS', '12'))
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '').strip()
GEMINI_CHATBOT_MODEL = os.getenv('GEMINI_CHATBOT_MODEL', 'gemini-flash-latest').strip() or 'gemini-flash-latest'
GEMINI_CHATBOT_TIMEOUT_SECONDS = int(os.getenv('GEMINI_CHATBOT_TIMEOUT_SECONDS', '20'))
GEMINI_CHATBOT_MAX_OUTPUT_TOKENS = int(os.getenv('GEMINI_CHATBOT_MAX_OUTPUT_TOKENS', '1200'))


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.core',
    'apps.asleb',
    'apps.barang_tertinggal',
    'apps.dashboard',
    'apps.inventaris',
    'apps.jadwal',
    'apps.kalender',
    'apps.peminjaman',
    'apps.pendaftaran_asleb',
    'apps.pengguna',
    'apps.ruangan',
    'apps.surat',
    'apps.mobile_api',
]

WHITENOISE_INSTALLED = find_spec('whitenoise') is not None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.pengguna.middleware.PenggunaLoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if WHITENOISE_INSTALLED:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'project_laboran.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.dashboard_sidebar',
                'apps.kalender.context_processors.kalender_notifikasi',
                'apps.pengguna.context_processors.pengguna_session',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_laboran.wsgi.application'
ASGI_APPLICATION = 'project_laboran.asgi.application'

CHANNEL_REDIS_URL = os.getenv('CHANNEL_REDIS_URL', '').strip()
if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [CHANNEL_REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_SQLITE_FOR_TESTS = os.getenv('USE_SQLITE_FOR_TESTS', 'False') == 'True'

if USE_SQLITE_FOR_TESTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'tmp' / 'test.sqlite3',
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'project_laboran'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = f'{URL_PREFIX}/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_USE_FINDERS = DEBUG
MEDIA_URL = os.getenv('MEDIA_URL', f'{URL_PREFIX}/media/')
MEDIA_ROOT = env_path('MEDIA_ROOT', 'media')

ABSENSI_CENTER_LATITUDE = float(os.getenv('ABSENSI_CENTER_LATITUDE', '-6.1680678'))
ABSENSI_CENTER_LONGITUDE = float(os.getenv('ABSENSI_CENTER_LONGITUDE', '106.7916257'))
ABSENSI_RADIUS_METERS = int(os.getenv('ABSENSI_RADIUS_METERS', '150'))
ABSENSI_MAX_GPS_ACCURACY_METERS = int(os.getenv('ABSENSI_MAX_GPS_ACCURACY_METERS', '100'))
ABSENSI_EARLY_CHECKIN_MINUTES = int(os.getenv('ABSENSI_EARLY_CHECKIN_MINUTES', '30'))
ABSENSI_MAX_PHOTO_SIZE_MB = int(os.getenv('ABSENSI_MAX_PHOTO_SIZE_MB', '5'))
ABSENSI_MAX_VIDEO_SIZE_MB = int(os.getenv('ABSENSI_MAX_VIDEO_SIZE_MB', '25'))
ABSENSI_MAX_VIDEO_DURATION_SECONDS = int(os.getenv('ABSENSI_MAX_VIDEO_DURATION_SECONDS', '15'))

MOBILE_JWT_ACCESS_MINUTES = int(os.getenv('MOBILE_JWT_ACCESS_MINUTES', '30'))
MOBILE_JWT_REFRESH_DAYS = int(os.getenv('MOBILE_JWT_REFRESH_DAYS', '7'))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.mobile_api.authentication.PenggunaJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.mobile_api.permissions.IsAsistenLab',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ricardo.dharma@trisakti.ac.id')

if USE_SQLITE_FOR_TESTS:
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
