from django.urls import path

from .views import (
    AbsensiAslebCreateView,
    AbsensiAslebListView,
    AslebCreateView,
    AslebDeleteView,
    AslebDetailView,
    AslebListView,
    AslebUpdateView,
    HonorAslebCreateView,
    HonorAslebDeleteView,
    HonorAslebListView,
    HonorAslebUpdateView,
    ModulPraktikumCreateView,
    ModulPraktikumDeleteView,
    ModulPraktikumUpdateView,
    LaporanPraktikumListView,
    PengumpulanLaporanPraktikumCreateView,
    ReviewLaporanPraktikumUpdateView,
    NilaiAbsensiMahasiswaView,
    PesertaPraktikumBulkCreateView,
    PesertaPraktikumUpdateView,
    PraktikumMahasiswaListView,
    SuratHonorAslebGenerateView,
    SuratHonorAslebListView,
    auto_assign_honor_transfers,
    confirm_honor_transfer,
    download_surat_honor,
    download_laporan_praktikum,
    download_modul_praktikum,
    preview_laporan_praktikum_file,
    preview_laporan_praktikum,
    preview_modul_praktikum,
    preview_modul_praktikum_page,
    TugasLaporanPraktikumCreateView,
    end_asleb_membership,
    export_nilai_praktikum_excel,
    bulk_delete_peserta_praktikum,
    delete_all_peserta_praktikum,
    delete_peserta_praktikum,
    toggle_absensi_status,
    update_transfer_fees,
    viewer_modul_praktikum,
)

app_name = 'asleb'

urlpatterns = [
    path('', AslebListView.as_view(), name='asleb_list'),
    path('tambah/', AslebCreateView.as_view(), name='asleb_create'),
    path('absensi/', AbsensiAslebListView.as_view(), name='absensi_list'),
    path('absensi/tambah/', AbsensiAslebCreateView.as_view(), name='absensi_create'),
    path('absensi/toggle/', toggle_absensi_status, name='absensi_toggle_status'),
    path('absensi/modul/tambah/', ModulPraktikumCreateView.as_view(), name='modul_create'),
    path('absensi/modul/<int:pk>/edit/', ModulPraktikumUpdateView.as_view(), name='modul_update'),
    path('absensi/modul/<int:pk>/hapus/', ModulPraktikumDeleteView.as_view(), name='modul_delete'),
    path('absensi/modul/<int:pk>/preview/', preview_modul_praktikum, name='modul_preview'),
    path('absensi/modul/<int:pk>/viewer/', viewer_modul_praktikum, name='modul_viewer'),
    path('absensi/modul/<int:pk>/preview/halaman/<int:page>.png', preview_modul_praktikum_page, name='modul_preview_page'),
    path('absensi/modul/<int:pk>/download/', download_modul_praktikum, name='modul_download'),
    path('praktikum-mahasiswa/', PraktikumMahasiswaListView.as_view(), name='praktikum_mahasiswa_list'),
    path('praktikum-mahasiswa/tambah/', PesertaPraktikumBulkCreateView.as_view(), name='praktikum_peserta_create'),
    path('praktikum-mahasiswa/export/', export_nilai_praktikum_excel, name='praktikum_nilai_export'),
    path('praktikum-mahasiswa/peserta/hapus-banyak/', bulk_delete_peserta_praktikum, name='praktikum_peserta_bulk_delete'),
    path('praktikum-mahasiswa/peserta/<int:pk>/edit/', PesertaPraktikumUpdateView.as_view(), name='praktikum_peserta_update'),
    path('praktikum-mahasiswa/<int:matkul_pk>/peserta/hapus-semua/', delete_all_peserta_praktikum, name='praktikum_peserta_delete_all'),
    path('praktikum-mahasiswa/peserta/<int:pk>/hapus/', delete_peserta_praktikum, name='praktikum_peserta_delete'),
    path('praktikum-mahasiswa/<int:matkul_pk>/modul/<int:modul_pk>/', NilaiAbsensiMahasiswaView.as_view(), name='praktikum_nilai'),
    path('laporan-praktikum/', LaporanPraktikumListView.as_view(), name='laporan_tugas_list'),
    path('laporan-praktikum/tugas/tambah/', TugasLaporanPraktikumCreateView.as_view(), name='laporan_tugas_create'),
    path('laporan-praktikum/tugas/<int:pk>/submit/', PengumpulanLaporanPraktikumCreateView.as_view(), name='laporan_submit'),
    path('laporan-praktikum/pengumpulan/<int:pk>/review/', ReviewLaporanPraktikumUpdateView.as_view(), name='laporan_review'),
    path('laporan-praktikum/pengumpulan/<int:pk>/preview/', preview_laporan_praktikum, name='laporan_preview'),
    path('laporan-praktikum/pengumpulan/<int:pk>/preview/file/', preview_laporan_praktikum_file, name='laporan_preview_file'),
    path('laporan-praktikum/pengumpulan/<int:pk>/download/', download_laporan_praktikum, name='laporan_download'),
    path('<int:pk>/', AslebDetailView.as_view(), name='asleb_detail'),
    path('<int:pk>/edit/', AslebUpdateView.as_view(), name='asleb_update'),
    path('<int:pk>/akhiri-masa-tugas/', end_asleb_membership, name='asleb_end_membership'),
    path('<int:pk>/hapus/', AslebDeleteView.as_view(), name='asleb_delete'),
    path('honorarium/', HonorAslebListView.as_view(), name='honor_list'),
    path('honorarium/surat/', SuratHonorAslebListView.as_view(), name='surat_honor_list'),
    path('honorarium/surat/generate/', SuratHonorAslebGenerateView.as_view(), name='surat_honor_generate'),
    path('honorarium/surat/<int:pk>/download/', download_surat_honor, name='surat_honor_download'),
    path('honorarium/tambah/', HonorAslebCreateView.as_view(), name='honor_create'),
    path('honorarium/bagi-tugas-tf/', auto_assign_honor_transfers, name='honor_auto_assign_transfers'),
    path('honorarium/biaya-transfer/', update_transfer_fees, name='honor_transfer_fees'),
    path('honorarium/<int:pk>/konfirmasi-tf/', confirm_honor_transfer, name='honor_confirm_transfer'),
    path('honorarium/<int:pk>/edit/', HonorAslebUpdateView.as_view(), name='honor_update'),
    path('honorarium/<int:pk>/hapus/', HonorAslebDeleteView.as_view(), name='honor_delete'),
]
