# Generated by Django 4.2.23 on 2026-06-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_seed_fakultas_prodi'),
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatankalender',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_kalender', to='pengguna.pengguna'),
        ),
        migrations.AddField(
            model_name='kegiatankalender',
            name='target_role',
            field=models.CharField(blank=True, help_text='Role yang bisa melihat kegiatan ini, dipisahkan koma.', max_length=120),
        ),
    ]
