# Generated by Django 4.2.23 on 2026-06-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0010_pengguna_cv'),
        ('kalender', '0002_kegiatankalender_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=160)),
                ('judul', models.CharField(max_length=220)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal', models.DateField()),
                ('waktu_label', models.CharField(blank=True, max_length=80)),
                ('lokasi', models.CharField(blank=True, max_length=180)),
                ('url', models.CharField(blank=True, max_length=240)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(default='bell', max_length=50)),
                ('icon_class', models.CharField(default='bg-slate-100 text-slate-600', max_length=120)),
                ('source_updated_at', models.DateTimeField()),
                ('dibaca_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='pengguna.pengguna')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-source_updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='notifikasi',
            constraint=models.UniqueConstraint(fields=('pengguna', 'source_key'), name='unique_notifikasi_per_pengguna_source'),
        ),
    ]
