# Generated by Django 4.2.23 on 2026-09-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0008_separate_lab_head_and_laboran'),
        ('kalender', '0004_kegiatankalender_hari_libur'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatankalender',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kegiatan_kalender', to='ruangan.ruanganlab'),
        ),
    ]
