# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Asleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nim', models.CharField('NIM', max_length=30, unique=True)),
                ('no_hp', models.CharField('No HP', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('program_studi', models.CharField(max_length=120)),
                ('semester', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=20)),
                ('tanggal_bergabung', models.DateField()),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
                'verbose_name': 'Asleb',
                'verbose_name_plural': 'Data Asleb',
            },
        ),
    ]
