# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asleb',
            name='matkul',
            field=models.CharField('Matkul', blank=True, max_length=200),
        ),
    ]
