# Generated by Django 4.2.23 on 2026-06-24 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0002_asleb_matkul'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField(default=django.utils.timezone.localdate)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diproses', 'Diproses'), ('dibayar', 'Dibayar')], default='draft', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('asleb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorarium', to='asleb.asleb')),
            ],
            options={
                'verbose_name': 'Honor Asleb',
                'verbose_name_plural': 'Honor Asleb',
                'ordering': ['-bulan', 'asleb__nama'],
            },
        ),
    ]
