# Generated by Django 4.2.23 on 2026-06-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0003_honorasleb'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorasleb',
            name='jumlah_praktikum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], default='junior', max_length=20),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='pic_transfer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='total_pertemuan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
