# Generated by Django 4.2.23 on 2026-06-24 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0004_honorasleb_jumlah_praktikum_honorasleb_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanAbsensiAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuka', models.BooleanField(default=False)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Absensi Asleb',
                'verbose_name_plural': 'Pengaturan Absensi Asleb',
            },
        ),
        migrations.CreateModel(
            name='AbsensiAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_praktikum', models.DateField(default=django.utils.timezone.localdate)),
                ('modul', models.PositiveSmallIntegerField(choices=[(1, 'Modul 1'), (2, 'Modul 2'), (3, 'Modul 3'), (4, 'Modul 4'), (5, 'Modul 5'), (6, 'Modul 6'), (7, 'Modul 7'), (8, 'Modul 8'), (9, 'Modul 9'), (10, 'Modul 10'), (11, 'Modul 11'), (12, 'Modul 12'), (13, 'Modul 13'), (14, 'Modul 14'), (15, 'Modul 15'), (16, 'Modul 16')])),
                ('materi_praktikum', models.CharField(blank=True, max_length=200)),
                ('pekerjaan', models.TextField(blank=True)),
                ('file_modul', models.FileField(upload_to='absensi_asleb/modul/', verbose_name='Upload Modul Praktikum')),
                ('bukti_video', models.FileField(upload_to='absensi_asleb/video/', verbose_name='Bukti Video Praktikum')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('asleb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='asleb.asleb')),
            ],
            options={
                'verbose_name': 'Absensi Asleb',
                'verbose_name_plural': 'Absensi Asleb',
                'ordering': ['-tanggal_praktikum', 'asleb__nama', 'modul'],
            },
        ),
        migrations.AddConstraint(
            model_name='absensiasleb',
            constraint=models.UniqueConstraint(fields=('asleb', 'modul'), name='unique_absensi_asleb_per_modul'),
        ),
    ]
