# Generated by Django 4.2.23 on 2026-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0005_pengaturanabsensiasleb_absensiasleb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorasleb',
            name='metode_transfer',
            field=models.CharField(choices=[('rekening_bank', 'Rekening Bank'), ('dana', 'DANA'), ('ovo', 'OVO')], default='rekening_bank', max_length=30),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='nama_pemilik_transfer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Pemilik Rekening/E-Wallet'),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='nomor_transfer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomor Rekening/E-Wallet'),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='tanggal_transfer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
