# Generated by Django 4.2.23 on 2026-06-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0006_honorasleb_metode_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiasleb',
            name='file_modul_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='honorasleb',
            name='bukti_transfer',
            field=models.FileField(blank=True, upload_to='honor_asleb/bukti_transfer/', verbose_name='Bukti Screenshot Transfer'),
        ),
    ]
