# Generated by Django 4.2.23 on 2026-06-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_seed_fakultas_prodi'),
        ('asleb', '0007_absensiasleb_file_modul_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorasleb',
            name='assigned_laboran',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'laboran'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_transfer_honor', to='pengguna.pengguna', verbose_name='Laboran Penanggung Jawab TF'),
        ),
    ]
