# Generated by Django 4.2.23 on 2026-06-26 08:17

import apps.asleb.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_reset_master_akademik_fti'),
        ('asleb', '0008_honorasleb_assigned_laboran'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratHonorAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('nomor_surat', models.CharField(max_length=120)),
                ('tanggal_surat', models.DateField(default=django.utils.timezone.localdate)),
                ('perihal', models.CharField(default='Laporan Kegiatan Asisten Laboratorium Jurusan Teknik Informatika', max_length=200)),
                ('file_pdf', models.FileField(upload_to='surat_honor_asleb/')),
                ('total_honor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('jumlah_asleb', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateField(default=apps.asleb.models.default_surat_honor_expires_at)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_honor_dibuat', to='pengguna.pengguna')),
            ],
            options={
                'verbose_name': 'Surat Honor Asleb',
                'verbose_name_plural': 'Arsip Surat Honor Asleb',
                'ordering': ['-bulan', '-dibuat_pada'],
            },
        ),
    ]
