# Generated by Django 4.2.23 on 2026-06-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0009_surathonorasleb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absensiasleb',
            options={'ordering': ['-tanggal_praktikum', 'asleb__nama', 'modul'], 'verbose_name': 'Absensi Aslab', 'verbose_name_plural': 'Absensi Aslab'},
        ),
        migrations.AlterModelOptions(
            name='asleb',
            options={'ordering': ['nama'], 'verbose_name': 'Aslab', 'verbose_name_plural': 'Data Aslab'},
        ),
        migrations.AlterModelOptions(
            name='honorasleb',
            options={'ordering': ['-bulan', 'asleb__nama'], 'verbose_name': 'Honor Aslab', 'verbose_name_plural': 'Honor Aslab'},
        ),
        migrations.AlterModelOptions(
            name='pengaturanabsensiasleb',
            options={'verbose_name': 'Pengaturan Absensi Aslab', 'verbose_name_plural': 'Pengaturan Absensi Aslab'},
        ),
        migrations.AlterModelOptions(
            name='surathonorasleb',
            options={'ordering': ['-bulan', '-dibuat_pada'], 'verbose_name': 'Surat Honor Aslab', 'verbose_name_plural': 'Arsip Surat Honor Aslab'},
        ),
    ]
