# Generated by Django 4.2.23 on 2026-06-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0010_pengguna_cv'),
        ('pendaftaran_asleb', '0008_alter_matakuliahasleb_options_and_more'),
        ('asleb', '0010_alter_absensiasleb_options_alter_asleb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulPraktikum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveSmallIntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='modul_praktikum/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modul Praktikum',
                'verbose_name_plural': 'Modul Praktikum',
                'ordering': ['matkul__nama', 'matkul__kelas', 'nomor'],
            },
        ),
        migrations.AddField(
            model_name='modulpraktikum',
            name='diunggah_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modul_praktikum_diunggah', to='pengguna.pengguna'),
        ),
        migrations.AddField(
            model_name='modulpraktikum',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modul_praktikum', to='pendaftaran_asleb.matakuliahasleb'),
        ),
        migrations.AddField(
            model_name='absensiasleb',
            name='modul_praktikum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absensi', to='asleb.modulpraktikum'),
        ),
        migrations.AddConstraint(
            model_name='absensiasleb',
            constraint=models.UniqueConstraint(fields=('asleb', 'modul_praktikum'), name='unique_absensi_asleb_per_modul_praktikum'),
        ),
        migrations.AddConstraint(
            model_name='modulpraktikum',
            constraint=models.UniqueConstraint(fields=('matkul', 'nomor'), name='unique_nomor_modul_per_matkul'),
        ),
    ]
