# Generated by Django 4.2.23 on 2026-06-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0004_jadwal_status'),
        ('asleb', '0011_modulpraktikum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiasleb',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absensi_asleb', to='jadwal.jadwalpraktikum'),
        ),
        migrations.AddField(
            model_name='absensiasleb',
            name='jarak_lokasi_meter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absensiasleb',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='absensiasleb',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PengingatAbsensiAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('tahap', models.PositiveSmallIntegerField()),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True)),
                ('asleb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengingat_absensi', to='asleb.asleb')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengingat_absensi_asleb', to='jadwal.jadwalpraktikum')),
            ],
            options={
                'verbose_name': 'Pengingat Absensi Aslab',
                'verbose_name_plural': 'Pengingat Absensi Aslab',
                'ordering': ['tanggal', 'jadwal__waktu_mulai', 'tahap'],
            },
        ),
        migrations.AddConstraint(
            model_name='pengingatabsensiasleb',
            constraint=models.UniqueConstraint(fields=('asleb', 'jadwal', 'tanggal', 'tahap'), name='unique_pengingat_absensi_asleb'),
        ),
    ]
