# Generated by Django 4.2.23 on 2026-06-28 13:40

from django.db import migrations, models
import django.db.models.deletion


def assign_active_periods(apps, schema_editor):
    Asleb = apps.get_model('asleb', 'Asleb')
    Registration = apps.get_model('pendaftaran_asleb', 'PendaftaranAsleb')
    for asleb in Asleb.objects.filter(status='aktif', periode_aktif__isnull=True):
        registration = Registration.objects.filter(
            nim=asleb.nim,
            status__in=['diterima', 'digenerate'],
            periode__isnull=False,
        ).order_by('-periode__tahun', '-periode__semester', '-pk').first()
        if registration:
            asleb.periode_aktif = registration.periode
            asleb.save(update_fields=['periode_aktif'])


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0009_periodeasleb_and_more'),
        ('asleb', '0012_absensiasleb_jadwal_absensiasleb_jarak_lokasi_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asleb',
            name='periode_aktif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asleb_aktif', to='pendaftaran_asleb.periodeasleb'),
        ),
        migrations.RunPython(assign_active_periods, migrations.RunPython.noop),
    ]
