# Generated by Django 4.2.23 on 2026-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0013_asleb_periode_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiasleb',
            name='bukti_foto',
            field=models.ImageField(blank=True, upload_to='absensi_asleb/foto/', verbose_name='Bukti Foto Praktikum'),
        ),
    ]
