# Generated by Django 4.2.23 on 2026-07-02 01:20

from django.db import migrations, models


def migrate_legacy_bank(apps, schema_editor):
    HonorAsleb = apps.get_model('asleb', 'HonorAsleb')
    for honor in HonorAsleb.objects.filter(metode_transfer='rekening_bank'):
        honor.metode_transfer = 'bank_lain'
        honor.biaya_admin = 2500
        honor.jumlah = max(honor.jumlah - 2500, 0)
        honor.save(update_fields=['metode_transfer', 'biaya_admin', 'jumlah'])


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0015_pesertapraktikum_hasilpraktikummahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorasleb',
            name='biaya_admin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(migrate_legacy_bank, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='honorasleb',
            name='metode_transfer',
            field=models.CharField(choices=[('bni', 'BNI'), ('bank_lain', 'Bank lain'), ('dana', 'DANA'), ('shopeepay', 'ShopeePay'), ('gopay', 'GoPay'), ('ovo', 'OVO')], default='bni', max_length=30),
        ),
    ]
