# Generated by Django 4.2.23 on 2026-07-03 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0006_permintaanperubahanjadwal'),
        ('asleb', '0016_honorasleb_biaya_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiMasukAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_absensi', models.DateField(default=django.utils.timezone.localdate)),
                ('waktu_masuk', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('jarak_lokasi_meter', models.DecimalField(decimal_places=2, max_digits=9)),
                ('akurasi_gps_meter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('sudah_absen', 'Sudah Absen'), ('terlambat', 'Terlambat')], default='sudah_absen', max_length=20)),
                ('foto_absensi', models.ImageField(upload_to='absensi_asleb/masuk/foto/%Y/%m/')),
                ('video_absensi', models.FileField(blank=True, upload_to='absensi_asleb/masuk/video/%Y/%m/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('asleb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absensi_masuk', to='asleb.asleb')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absensi_masuk_asleb', to='jadwal.jadwalpraktikum')),
            ],
            options={
                'verbose_name': 'Absensi Masuk Aslab',
                'verbose_name_plural': 'Absensi Masuk Aslab',
                'ordering': ['-tanggal_absensi', '-waktu_masuk'],
            },
        ),
        migrations.AddConstraint(
            model_name='absensimasukasleb',
            constraint=models.UniqueConstraint(fields=('asleb', 'jadwal', 'tanggal_absensi'), name='unique_absensi_masuk_asleb_jadwal_tanggal'),
        ),
    ]
