# Generated by Django 4.2.23 on 2026-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0017_absensimasukasleb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensimasukasleb',
            name='akurasi_gps_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='absensimasukasleb',
            name='jarak_lokasi_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='absensimasukasleb',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='absensimasukasleb',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
