# Generated by Django 4.2.23 on 2026-07-07 01:52

from django.db import migrations, models
import django.db.models.deletion


def populate_hasil_snapshot(apps, schema_editor):
    HasilPraktikumMahasiswa = apps.get_model('asleb', 'HasilPraktikumMahasiswa')
    for hasil in HasilPraktikumMahasiswa.objects.select_related('peserta', 'peserta__matkul').all():
        if not hasil.peserta_id:
            continue
        hasil.peserta_nim = hasil.peserta.nim
        hasil.peserta_nama = hasil.peserta.nama
        hasil.matkul_label = str(hasil.peserta.matkul)
        hasil.save(update_fields=['peserta_nim', 'peserta_nama', 'matkul_label'])


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0018_alter_absensimasukasleb_akurasi_gps_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='matkul_label',
            field=models.CharField(blank=True, max_length=250, verbose_name='Mata kuliah'),
        ),
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='peserta_nama',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama peserta'),
        ),
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='peserta_nim',
            field=models.CharField(blank=True, max_length=40, verbose_name='NIM peserta'),
        ),
        migrations.AlterField(
            model_name='hasilpraktikummahasiswa',
            name='peserta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasil_praktikum', to='asleb.pesertapraktikum'),
        ),
        migrations.RunPython(populate_hasil_snapshot, migrations.RunPython.noop),
    ]
