# Generated by Django 4.2.23 on 2026-07-07 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0019_hasilpraktikummahasiswa_matkul_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='nilai_laporan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai laporan'),
        ),
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='nilai_realtime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai realtime'),
        ),
    ]
