# Generated by Django 4.2.23 on 2026-07-09 10:28

from django.db import migrations, models
import django.db.models.deletion


def copy_modul_snapshot(apps, schema_editor):
    HasilPraktikumMahasiswa = apps.get_model('asleb', 'HasilPraktikumMahasiswa')
    for hasil in HasilPraktikumMahasiswa.objects.select_related('modul', 'modul__matkul').all():
        if not hasil.modul_id:
            continue
        modul = hasil.modul
        hasil.modul_nomor = modul.nomor
        hasil.modul_judul = modul.judul
        if not hasil.matkul_label:
            matkul = modul.matkul
            kode = getattr(matkul, 'kode_mk', '') or getattr(matkul, 'kode', '') or ''
            kelas = getattr(matkul, 'kelas', '') or ''
            nama = getattr(matkul, 'nama', '') or ''
            prefix = f'{kode} - ' if kode else ''
            suffix = f' - {kelas}' if kelas else ''
            hasil.matkul_label = f'{prefix}{nama}{suffix}'.strip()
        hasil.save(update_fields=['modul_nomor', 'modul_judul', 'matkul_label'])


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0020_hasil_praktikum_dua_nilai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hasilpraktikummahasiswa',
            options={'ordering': ['modul_nomor', 'peserta__nama'], 'verbose_name': 'Nilai dan Absensi Mahasiswa', 'verbose_name_plural': 'Nilai dan Absensi Mahasiswa'},
        ),
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='modul_judul',
            field=models.CharField(blank=True, max_length=200, verbose_name='Judul modul'),
        ),
        migrations.AddField(
            model_name='hasilpraktikummahasiswa',
            name='modul_nomor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nomor modul'),
        ),
        migrations.RunPython(copy_modul_snapshot, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='absensiasleb',
            name='modul_praktikum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi', to='asleb.modulpraktikum'),
        ),
        migrations.AlterField(
            model_name='hasilpraktikummahasiswa',
            name='modul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasil_mahasiswa', to='asleb.modulpraktikum'),
        ),
    ]
