# Generated by Django 4.2.23 on 2026-07-09 18:51

from django.db import migrations, models


def ensure_modul_columns(apps, schema_editor):
    table_name = schema_editor.quote_name('asleb_modulpraktikum')
    vendor = schema_editor.connection.vendor
    if vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS file_size bigint NULL"
            )
            cursor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS file_type varchar(20) NOT NULL DEFAULT ''"
            )
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN file_size bigint NULL")
        cursor.execute(
            f"ALTER TABLE {table_name} ADD COLUMN file_type varchar(20) NOT NULL DEFAULT ''"
        )


def populate_modul_file_metadata(apps, schema_editor):
    ModulPraktikum = apps.get_model('asleb', 'ModulPraktikum')
    for modul in ModulPraktikum.objects.all():
        filename = (modul.file.name or '').lower()
        if filename.endswith('.pdf'):
            modul.file_type = 'pdf'
        elif filename.endswith('.doc'):
            modul.file_type = 'doc'
        elif filename.endswith('.docx'):
            modul.file_type = 'docx'
        try:
            modul.file_size = modul.file.size
        except Exception:
            pass
        modul.save(update_fields=['file_type', 'file_size'])


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0021_alter_hasilpraktikummahasiswa_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_modul_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='modulpraktikum',
                    name='file_size',
                    field=models.PositiveBigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='modulpraktikum',
                    name='file_type',
                    field=models.CharField(blank=True, max_length=20),
                ),
            ],
        ),
        migrations.RunPython(populate_modul_file_metadata, migrations.RunPython.noop),
    ]
