# Generated by Django 4.2.23 on 2026-07-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0026_normalize_mobile_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumpulanlaporanpraktikum',
            name='status',
            field=models.CharField(choices=[('belum_dikumpulkan', 'Belum dikumpulkan'), ('sudah_dikumpulkan', 'Sudah dikumpulkan'), ('terlambat', 'Terlambat'), ('sedang_diperiksa', 'Sedang diperiksa'), ('perlu_revisi', 'Perlu revisi'), ('sudah_direvisi', 'Sudah direvisi'), ('diterima', 'Diterima'), ('sudah_dinilai', 'Sudah dinilai'), ('dibatalkan', 'Dibatalkan')], default='sudah_dikumpulkan', max_length=30),
        ),
    ]
