# Generated by Django 4.2.23 on 2026-07-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0027_honor_reassignment_audit'),
        ('asleb', '0028_honor_financial_integrity'),
    ]

    operations = [
    ]
