# Generated by Django 5.2.16 on 2026-08-31 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0030_absensi_asleb_periode'),
        ('pengguna', '0016_rename_pengguna_sc_npsn_36628f_idx_pengguna_sc_npsn_495644_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asleb',
            name='level_diatur_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaturan_level_asleb', to='pengguna.pengguna'),
        ),
        migrations.AddField(
            model_name='asleb',
            name='level_diatur_pada',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asleb',
            name='level_manual',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=20, verbose_name='Level manual'),
        ),
        migrations.AddField(
            model_name='asleb',
            name='level_mode',
            field=models.CharField(choices=[('otomatis', 'Otomatis'), ('manual', 'Manual oleh Laboran')], default='otomatis', max_length=20, verbose_name='Mode level'),
        ),
    ]
