# Generated by Django 4.2.23 on 2026-09-30 07:20

from django.db import migrations, models
import django.db.models.deletion


def backfill_mobile_attendance_context(apps, schema_editor):
    AbsensiAsleb = apps.get_model('asleb', 'AbsensiAsleb')
    AbsensiMasukAsleb = apps.get_model('asleb', 'AbsensiMasukAsleb')
    PeriodeAsleb = apps.get_model('pendaftaran_asleb', 'PeriodeAsleb')

    periods = list(PeriodeAsleb.objects.order_by('-mulai', '-pk'))
    for attendance in AbsensiMasukAsleb.objects.all().iterator():
        period = next(
            (
                item for item in periods
                if item.mulai <= attendance.tanggal_absensi <= item.selesai
            ),
            None,
        )
        matching_web = (
            AbsensiAsleb.objects.filter(
                asleb_id=attendance.asleb_id,
                jadwal_id=attendance.jadwal_id,
                tanggal_praktikum=attendance.tanggal_absensi,
                modul_praktikum_id__isnull=False,
            )
            .order_by('pk')
            .first()
        )
        attendance.periode_id = matching_web.periode_id if matching_web else getattr(period, 'pk', None)
        attendance.modul_praktikum_id = (
            matching_web.modul_praktikum_id if matching_web else None
        )
        attendance.save(update_fields=['periode', 'modul_praktikum'])


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0021_keputusanseleksiasleb'),
        ('asleb', '0033_honor_asleb_module_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensimasukasleb',
            name='modul_praktikum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_masuk_mobile', to='asleb.modulpraktikum'),
        ),
        migrations.AddField(
            model_name='absensimasukasleb',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_masuk_asleb', to='pendaftaran_asleb.periodeasleb'),
        ),
        migrations.RunPython(
            backfill_mobile_attendance_context,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='absensimasukasleb',
            constraint=models.UniqueConstraint(fields=('asleb', 'periode', 'modul_praktikum'), name='unique_absensi_masuk_asleb_periode_modul'),
        ),
    ]
