# Generated by Django 4.2.23 on 2026-06-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengguna', '0010_pengguna_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercakapanBantuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bot', 'Chat Bot'), ('admin', 'Menunggu Admin'), ('selesai', 'Selesai')], default='bot', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percakapan_bantuan', to='pengguna.pengguna')),
            ],
            options={
                'verbose_name': 'Percakapan Bantuan',
                'verbose_name_plural': 'Percakapan Bantuan',
                'ordering': ['-diperbarui_pada'],
            },
        ),
        migrations.CreateModel(
            name='PesanBantuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('pengguna', 'Pengguna'), ('bot', 'Bot'), ('admin', 'Admin')], max_length=20)),
                ('isi', models.TextField(max_length=1000)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('percakapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='core.percakapanbantuan')),
            ],
            options={
                'verbose_name': 'Pesan Bantuan',
                'verbose_name_plural': 'Pesan Bantuan',
                'ordering': ['dibuat_pada', 'pk'],
            },
        ),
    ]
