# Generated by Django 4.2.23 on 2026-07-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0014_pengalamanpengguna_file_sertifikat_and_more'),
        ('core', '0004_relax_legacy_bugerrorlog_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugerrorlog',
            name='ditangani_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_error_ditangani', to='pengguna.pengguna'),
        ),
    ]
