from django.urls import path

from .views import (
    AttendanceHistoryView,
    AslebAdminChatView,
    ChatbotView,
    CheckInView,
    DashboardView,
    LocationConfigView,
    LaboranDashboardView,
    LaboranInventoryListCreateView,
    LaboranInventoryDetailView,
    LaboranLoanListView,
    LaboranLoanStatusView,
    LaboranLostItemCreateView,
    LaboranLocationListView,
    LoginView,
    LogoutView,
    MahasiswaLoanListView,
    MobileMediaView,
    ProfileView,
    RefreshTokenView,
    ScheduleDetailView,
    ScheduleListView,
)

app_name = 'mobile_api'

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/refresh/', RefreshTokenView.as_view(), name='refresh'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('media/<path:path>/', MobileMediaView.as_view(), name='media'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('mahasiswa/loans/', MahasiswaLoanListView.as_view(), name='mahasiswa_loans'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('schedules/', ScheduleListView.as_view(), name='schedule_list'),
    path('schedules/<int:pk>/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('attendance/check-in/', CheckInView.as_view(), name='check_in'),
    path('attendance/history/', AttendanceHistoryView.as_view(), name='attendance_history'),
    path('chatbot/', ChatbotView.as_view(), name='chatbot'),
    path('chat-admin/', AslebAdminChatView.as_view(), name='chat_admin'),
    path('config/location/', LocationConfigView.as_view(), name='location_config'),
    path('laboran/dashboard/', LaboranDashboardView.as_view(), name='laboran_dashboard'),
    path('laboran/locations/', LaboranLocationListView.as_view(), name='laboran_locations'),
    path('laboran/inventory/', LaboranInventoryListCreateView.as_view(), name='laboran_inventory'),
    path(
        'laboran/inventory/<int:pk>/',
        LaboranInventoryDetailView.as_view(),
        name='laboran_inventory_detail',
    ),
    path('laboran/loans/', LaboranLoanListView.as_view(), name='laboran_loans'),
    path('laboran/loans/<int:pk>/status/', LaboranLoanStatusView.as_view(), name='laboran_loan_status'),
    path('laboran/lost-items/', LaboranLostItemCreateView.as_view(), name='laboran_lost_item_create'),
]
