# Generated by Django 4.2.23 on 2026-07-02 05:40

from django.db import migrations


def update_capacities(apps, schema_editor):
    RuanganLab = apps.get_model('ruangan', 'RuanganLab')
    RuanganLab.objects.filter(kode='LAB-SDA').update(kapasitas=20)
    RuanganLab.objects.filter(kode='LAB-RD').update(kapasitas=30)


def restore_capacities(apps, schema_editor):
    RuanganLab = apps.get_model('ruangan', 'RuanganLab')
    RuanganLab.objects.filter(kode='LAB-SDA').update(kapasitas=13)
    RuanganLab.objects.filter(kode='LAB-RD').update(kapasitas=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ruangan', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_capacities, restore_capacities),
    ]
