# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PendaftaranAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('nim', models.CharField('NIM', max_length=30)),
                ('no_hp', models.CharField('No HP', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('program_studi', models.CharField(max_length=120)),
                ('semester', models.PositiveSmallIntegerField()),
                ('matkul', models.CharField('Matkul', max_length=200)),
                ('alasan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diajukan', max_length=20)),
                ('tanggal_daftar', models.DateField(auto_now_add=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tanggal_daftar', 'nama'],
                'verbose_name': 'Pendaftaran Asleb',
                'verbose_name_plural': 'Pendaftaran Asleb',
            },
        ),
    ]
