# Generated by Django 4.2.23 on 2026-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0003_matakuliah_asleb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPendaftaranAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuka', models.BooleanField(default=False)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Pendaftaran Asleb',
                'verbose_name_plural': 'Pengaturan Pendaftaran Asleb',
            },
        ),
    ]
