# Generated by Django 4.2.23 on 2026-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0004_pengaturanpendaftaranasleb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendaftaranasleb',
            options={'ordering': ['matkul__nama', 'matkul__kelas', '-skor_nilai', 'dibuat_pada', 'nama'], 'verbose_name': 'Pendaftaran Asleb', 'verbose_name_plural': 'Pendaftaran Asleb'},
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='metode_rekening',
            field=models.CharField(choices=[('rekening_bank', 'Rekening Bank'), ('dana', 'DANA'), ('ovo', 'OVO')], default='rekening_bank', max_length=30),
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='nilai_transkrip',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('tidak_terbaca', 'Tidak terbaca')], default='tidak_terbaca', max_length=20),
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='skor_nilai',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
