# Generated by Django 4.2.23 on 2026-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0005_alter_pendaftaranasleb_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='tanda_tangan',
            field=models.ImageField(blank=True, upload_to='pendaftaran_asleb/tanda_tangan/', verbose_name='Tanda Tangan'),
        ),
    ]
