# Generated by Django 4.2.23 on 2026-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0006_pendaftaranasleb_tanda_tangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaranasleb',
            name='nilai_transkrip',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('tidak_terbaca', 'Tidak terbaca')], default='tidak_terbaca', max_length=20),
        ),
    ]
