# Generated by Django 4.2.23 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0007_alter_pendaftaranasleb_nilai_transkrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliahasleb',
            options={'ordering': ['nama', 'kelas', 'dosen'], 'verbose_name': 'Mata Kuliah Aslab', 'verbose_name_plural': 'Mata Kuliah Aslab'},
        ),
        migrations.AlterModelOptions(
            name='pendaftaranasleb',
            options={'ordering': ['matkul__nama', 'matkul__kelas', '-skor_nilai', 'dibuat_pada', 'nama'], 'verbose_name': 'Pendaftaran Aslab', 'verbose_name_plural': 'Pendaftaran Aslab'},
        ),
        migrations.AlterModelOptions(
            name='pengaturanpendaftaranasleb',
            options={'verbose_name': 'Pengaturan Pendaftaran Aslab', 'verbose_name_plural': 'Pengaturan Pendaftaran Aslab'},
        ),
        migrations.AlterField(
            model_name='pendaftaranasleb',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('digenerate', 'Masuk Data Aslab')], default='diajukan', max_length=20),
        ),
    ]
