# Generated by Django 4.2.23 on 2026-06-28 13:40

from django.db import migrations, models
import django.db.models.deletion
from datetime import date, timedelta


def assign_existing_registrations(apps, schema_editor):
    Period = apps.get_model('pendaftaran_asleb', 'PeriodeAsleb')
    Registration = apps.get_model('pendaftaran_asleb', 'PendaftaranAsleb')
    for registration in Registration.objects.filter(periode__isnull=True):
        registered_on = registration.tanggal_daftar or registration.dibuat_pada.date()
        semester = 1 if registered_on.month <= 6 else 2
        start_month = 1 if semester == 1 else 7
        end_month = 6 if semester == 1 else 12
        period, _ = Period.objects.get_or_create(
            tahun=registered_on.year,
            semester=semester,
            defaults={
                'mulai': date(registered_on.year, start_month, 1),
                'selesai': date(registered_on.year, end_month, 30 if end_month == 6 else 31),
                'pendaftaran_mulai': date(registered_on.year, start_month, 1),
                'pendaftaran_selesai': date(registered_on.year, start_month, 1) + timedelta(days=29),
            },
        )
        registration.periode = period
        registration.save(update_fields=['periode'])


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0008_alter_matakuliahasleb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Januari - Juni'), (2, 'Juli - Desember')])),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('pendaftaran_mulai', models.DateField()),
                ('pendaftaran_selesai', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periode Aslab',
                'verbose_name_plural': 'Periode Aslab',
                'ordering': ['-tahun', '-semester'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodeasleb',
            constraint=models.UniqueConstraint(fields=('tahun', 'semester'), name='unique_periode_asleb_per_semester'),
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran', to='pendaftaran_asleb.periodeasleb'),
        ),
        migrations.RunPython(assign_existing_registrations, migrations.RunPython.noop),
    ]
