# Generated by Django 4.2.23 on 2026-06-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0009_periodeasleb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliahasleb',
            name='kode_mk',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Kode Mata Kuliah'),
        ),
        migrations.AddField(
            model_name='matakuliahasleb',
            name='sks',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='SKS'),
        ),
    ]
