# Generated by Codex on 2026-06-30

from django.db import migrations


MATKUL_SEED = [
    ('IKD207', 'Social Network', 2),
    ('IKH208', 'Kapita Selekta', 2),
    ('IKH209', 'Internet of Things', 2),
    ('IEE317', 'Sistem Cerdas', 3),
    ('IEC310', 'Sistem Robotika', 3),
    ('ISP401', 'Enterprise Resource Planning', 4),
    ('IKL308', 'Agile Development', 3),
    ('IKD307', 'Data Intelligent', 3),
    ('IKD306', 'Penambangan Teks', 3),
    ('IED254', 'Biomedic Engineering', 2),
    ('IKG307', 'Pengolahan Multimedia', 3),
    ('IIIO302', 'Bisnis Berbasis Teknologi', 3),
    ('IIP338', 'Manajemen Rantai Pasok', 3),
    ('IKS207', 'Sistem Penginderaan Jarak Jauh', 2),
    ('ISM312', 'Manajemen Pengetahuan', 3),
    ('IKD416', 'Datawarehouse', 4),
    ('IKH205', 'Keamanan Internet', 2),
    ('IKH206', 'Keamanan Perangkat Bergerak', 2),
    ('IKH227', 'Keamanan Fisik', 2),
    ('IKS6316', 'Pemrograman Berorientasi Objek', 3),
    ('IKS6337', 'Pemrograman Berorientasi Objek Lanjut', 3),
    ('IKP6303', 'Pemrograman Mobile', 3),
    ('IKG6310', 'Pemrograman Game', 3),
    ('ISS6303', 'Kompetensi keahlian', 3),
    ('ISP6202', 'Rantai Pasok Digital', 3),
    ('ISW6201', 'Web Content Management', 2),
]


def seed_kode_mk_sks(apps, schema_editor):
    MataKuliahAsleb = apps.get_model('pendaftaran_asleb', 'MataKuliahAsleb')

    for kode_mk, nama, sks in MATKUL_SEED:
        matkul = (
            MataKuliahAsleb.objects.filter(kode_mk=kode_mk).first()
            or MataKuliahAsleb.objects.filter(kode=kode_mk).first()
        )

        if matkul:
            matkul.kode_mk = kode_mk
            matkul.nama = nama
            matkul.sks = sks
            matkul.aktif = True
            matkul.save(update_fields=['kode_mk', 'nama', 'sks', 'aktif'])
            continue

        MataKuliahAsleb.objects.create(
            kode=kode_mk,
            kode_mk=kode_mk,
            nama=nama,
            sks=sks,
            dosen='',
            kelas='',
            aktif=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0010_matakuliahasleb_kode_mk_matakuliahasleb_sks'),
    ]

    operations = [
        migrations.RunPython(seed_kode_mk_sks, migrations.RunPython.noop),
    ]
