# Generated by Django 4.2.23 on 2026-07-02 01:20

from django.db import migrations, models


def migrate_legacy_bank(apps, schema_editor):
    PendaftaranAsleb = apps.get_model('pendaftaran_asleb', 'PendaftaranAsleb')
    PendaftaranAsleb.objects.filter(metode_rekening='rekening_bank').update(metode_rekening='bank_lain')


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0011_seed_kode_mk_sks'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_bank, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pendaftaranasleb',
            name='metode_rekening',
            field=models.CharField(choices=[('bni', 'BNI (gratis biaya admin)'), ('bank_lain', 'Bank lain (biaya admin Rp2.500)'), ('dana', 'DANA (gratis biaya admin)'), ('shopeepay', 'ShopeePay (biaya admin Rp1.500)'), ('gopay', 'GoPay (biaya admin Rp1.500)'), ('ovo', 'OVO (biaya admin Rp1.500)')], default='bni', max_length=30),
        ),
    ]
