# Generated by Django 4.2.23 on 2026-07-02 05:40

from django.db import migrations, models


def populate_account_owners(apps, schema_editor):
    PendaftaranAsleb = apps.get_model('pendaftaran_asleb', 'PendaftaranAsleb')
    for registration in PendaftaranAsleb.objects.filter(nama_pemilik_rekening=''):
        registration.nama_pemilik_rekening = registration.nama
        registration.save(update_fields=['nama_pemilik_rekening'])


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0012_alter_pendaftaranasleb_metode_rekening'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanBiayaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaya_bni', models.PositiveIntegerField(default=0, verbose_name='Biaya BNI')),
                ('biaya_bank_lain', models.PositiveIntegerField(default=2500, verbose_name='Biaya Bank Lain')),
                ('biaya_dana', models.PositiveIntegerField(default=0, verbose_name='Biaya DANA')),
                ('biaya_shopeepay', models.PositiveIntegerField(default=1500, verbose_name='Biaya ShopeePay')),
                ('biaya_gopay', models.PositiveIntegerField(default=1500, verbose_name='Biaya GoPay')),
                ('biaya_ovo', models.PositiveIntegerField(default=1500, verbose_name='Biaya OVO')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Biaya Transfer',
                'verbose_name_plural': 'Pengaturan Biaya Transfer',
            },
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='nama_pemilik_rekening',
            field=models.CharField(blank=True, max_length=150, verbose_name='Atas Nama'),
        ),
        migrations.RunPython(populate_account_owners, migrations.RunPython.noop),
    ]
