# Generated by Django 4.2.23 on 2026-07-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0013_pengguna_cover_image'),
        ('pendaftaran_asleb', '0013_pengaturanbiayatransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeasleb',
            name='diakhiri_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode_asleb_diakhiri', to='pengguna.pengguna'),
        ),
        migrations.AddField(
            model_name='periodeasleb',
            name='diakhiri_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
