# Generated by Django 4.2.23 on 2026-07-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_asleb', '0014_periodeasleb_diakhiri_oleh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(db_index=True, max_length=30, verbose_name='NIM')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('metode_rekening', models.CharField(choices=[('bni', 'BNI (gratis biaya admin)'), ('bank_lain', 'Bank lain (biaya admin Rp2.500)'), ('dana', 'DANA (gratis biaya admin)'), ('shopeepay', 'ShopeePay (biaya admin Rp1.500)'), ('gopay', 'GoPay (biaya admin Rp1.500)'), ('ovo', 'OVO (biaya admin Rp1.500)')], max_length=30)),
                ('rekening', models.CharField(blank=True, max_length=150)),
                ('nama_pemilik_rekening', models.CharField(blank=True, max_length=150)),
                ('source_pendaftaran_id', models.PositiveBigIntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_asleb', to='pendaftaran_asleb.matakuliahasleb')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_asleb', to='pendaftaran_asleb.periodeasleb')),
            ],
            options={
                'verbose_name': 'Riwayat Aslab',
                'verbose_name_plural': 'Riwayat Aslab',
                'ordering': ['-periode__tahun', '-periode__semester', 'nama'],
            },
        ),
        migrations.AddConstraint(
            model_name='riwayatasleb',
            constraint=models.UniqueConstraint(fields=('nim', 'periode', 'matkul'), name='unique_riwayat_asleb_periode_matkul'),
        ),
        migrations.AddConstraint(
            model_name='riwayatasleb',
            constraint=models.UniqueConstraint(fields=('source_pendaftaran_id',), name='unique_source_pendaftaran_riwayat_asleb'),
        ),
    ]
