# Generated by Django 4.2.23 on 2026-07-22 02:12

from django.db import migrations, models
import django.db.models.deletion


def ensure_check_constraints_supported(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'mysql':
        return

    version = getattr(connection, 'mysql_version', None)
    is_mariadb = getattr(connection, 'mysql_is_mariadb', False)
    if not isinstance(version, (tuple, list)):
        raise RuntimeError(
            'Cannot determine the MySQL/MariaDB server version required '
            'for enforced CHECK constraints.'
        )

    version = tuple(version)
    if is_mariadb:
        if version < (10, 2, 1):
            raise RuntimeError(
                'Aslab assignment constraints require MariaDB 10.2.1 or newer '
                'with enforced CHECK constraints.'
            )
        return

    if version < (8, 0, 16):
        raise RuntimeError(
            'Aslab assignment constraints require MySQL 8.0.16 or newer '
            'with enforced CHECK constraints.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('asleb', '0026_normalize_mobile_attendance_status'),
        ('pengguna', '0016_rename_pengguna_sc_npsn_36628f_idx_pengguna_sc_npsn_495644_idx_and_more'),
        ('pendaftaran_asleb', '0015_riwayatasleb_and_more'),
    ]

    operations = [
        migrations.RunPython(
            ensure_check_constraints_supported,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AslabSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('vacant', 'Kosong'), ('closed', 'Ditutup')], default='active', max_length=12)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aslab_slots', to='pendaftaran_asleb.matakuliahasleb')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aslab_slots', to='pendaftaran_asleb.periodeasleb')),
            ],
            options={
                'verbose_name': 'Slot Aslab',
                'verbose_name_plural': 'Slot Aslab',
                'ordering': ['periode', 'matkul', 'nomor'],
            },
        ),
        migrations.CreateModel(
            name='AslabAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai_pada', models.DateField()),
                ('berakhir_pada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('active', 'Aktif'), ('resigned', 'Mengundurkan Diri'), ('terminated', 'Diberhentikan'), ('replaced', 'Digantikan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=16)),
                ('alasan_berakhir', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('active_slot', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_assignment', to='pendaftaran_asleb.aslabslot')),
                ('asleb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='asleb.asleb')),
                ('diakhiri_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_assignments_ended', to='pengguna.pengguna')),
                ('menggantikan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digantikan_oleh', to='pendaftaran_asleb.aslabassignment')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='pendaftaran_asleb.aslabslot')),
                ('source_pendaftaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_assignments', to='pendaftaran_asleb.pendaftaranasleb')),
            ],
            options={
                'verbose_name': 'Penugasan Aslab',
                'verbose_name_plural': 'Penugasan Aslab',
                'ordering': ['-mulai_pada', '-dibuat_pada'],
            },
        ),
        migrations.AddConstraint(
            model_name='aslabslot',
            constraint=models.CheckConstraint(check=models.Q(('nomor__in', [1, 2])), name='aslab_slot_number_1_or_2'),
        ),
        migrations.AddConstraint(
            model_name='aslabslot',
            constraint=models.UniqueConstraint(fields=('periode', 'matkul', 'nomor'), name='unique_aslab_slot'),
        ),
        migrations.AddConstraint(
            model_name='aslabassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active_slot', models.F('slot')), ('active_slot__isnull', False), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('active_slot__isnull', True)), _connector='OR'), name='active_assignment_slot_guard'),
        ),
    ]
