# Generated by Django 4.2.23 on 2026-07-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0016_rename_pengguna_sc_npsn_36628f_idx_pengguna_sc_npsn_495644_idx_and_more'),
        ('pendaftaran_asleb', '0017_backfill_aslab_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AslabReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('transfer_month', models.DateField()),
                ('method', models.CharField(choices=[('undecided', 'Belum Ditentukan'), ('direct_offer', 'Penawaran Langsung'), ('limited_registration', 'Pendaftaran Terbatas')], default='undecided', max_length=24)),
                ('status', models.CharField(choices=[('waiting_action', 'Menunggu Tindakan'), ('searching', 'Mencari Pengganti'), ('waiting_consent', 'Menunggu Persetujuan'), ('completing_data', 'Melengkapi Data'), ('waiting_verification', 'Menunggu Verifikasi'), ('active', 'Aktif'), ('cancelled', 'Dibatalkan')], default='waiting_action', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_replacements_activated', to='pengguna.pengguna')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aslab_replacements_created', to='pengguna.pengguna')),
                ('incoming_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_replacement_process', to='pendaftaran_asleb.aslabassignment')),
                ('outgoing_assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_process', to='pendaftaran_asleb.aslabassignment')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='pendaftaran_asleb.aslabslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='candidate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aslab_registrations', to='pengguna.pengguna'),
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='jenis',
            field=models.CharField(choices=[('regular', 'Reguler'), ('replacement', 'Pengganti')], default='regular', max_length=16),
        ),
        migrations.CreateModel(
            name='LimitedReplacementOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('program_studi', models.CharField(blank=True, max_length=120)),
                ('cohort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('open', 'Dibuka'), ('closed', 'Ditutup'), ('filled', 'Terisi')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_candidates', models.ManyToManyField(blank=True, related_name='limited_replacement_openings', to='pengguna.pengguna')),
                ('replacement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='limited_opening', to='pendaftaran_asleb.aslabreplacement')),
            ],
        ),
        migrations.CreateModel(
            name='AslabReplacementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('previous_state', models.CharField(blank=True, max_length=24)),
                ('new_state', models.CharField(blank=True, max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_replacement_audits', to='pengguna.pengguna')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='pendaftaran_asleb.aslabreplacement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AslabOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Menunggu'), ('accepted_incomplete', 'Diterima, Data Belum Lengkap'), ('submitted', 'Diajukan'), ('verified', 'Terverifikasi'), ('declined', 'Ditolak'), ('expired', 'Kedaluwarsa'), ('cancelled', 'Dibatalkan')], default='waiting', max_length=24)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aslab_offers', to='pengguna.pengguna')),
                ('live_replacement', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_offer', to='pendaftaran_asleb.aslabreplacement')),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_offer', to='pendaftaran_asleb.pendaftaranasleb')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='pendaftaran_asleb.aslabreplacement')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_offers_verified', to='pengguna.pengguna')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='pendaftaranasleb',
            name='replacement_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='pendaftaran_asleb.aslabreplacement'),
        ),
        migrations.AddConstraint(
            model_name='aslaboffer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('live_replacement', models.F('replacement')), ('live_replacement__isnull', False), ('status__in', ['waiting', 'accepted_incomplete', 'submitted'])), models.Q(models.Q(('status__in', ['waiting', 'accepted_incomplete', 'submitted']), _negated=True), ('live_replacement__isnull', True)), _connector='OR'), name='aslab_offer_live_replacement_guard'),
        ),
    ]
