# Generated by Django 4.2.23 on 2026-09-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0016_rename_pengguna_sc_npsn_36628f_idx_pengguna_sc_npsn_495644_idx_and_more'),
        ('pendaftaran_asleb', '0020_matkul_aslab_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeputusanSeleksiAsleb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(db_index=True, max_length=30)),
                ('source_pendaftaran_id', models.PositiveBigIntegerField()),
                ('nilai_tujuan', models.CharField(blank=True, max_length=2)),
                ('melewati_batas', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diatur_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keputusan_seleksi_asleb', to='pengguna.pengguna')),
                ('matkul_pilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keputusan_pilihan', to='pendaftaran_asleb.matakuliahasleb')),
                ('matkul_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keputusan_tujuan', to='pendaftaran_asleb.matakuliahasleb')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pendaftaran_asleb.periodeasleb')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
