# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwalpraktikum',
            old_name='mata_praktikum',
            new_name='mata_kuliah',
        ),
        migrations.RenameField(
            model_name='jadwalpraktikum',
            old_name='ruangan',
            new_name='letak_ruangan',
        ),
        migrations.AlterField(
            model_name='jadwalpraktikum',
            name='mata_kuliah',
            field=models.CharField('Matkul', max_length=200),
        ),
        migrations.AlterField(
            model_name='jadwalpraktikum',
            name='letak_ruangan',
            field=models.CharField('Letak Ruangan', max_length=150),
        ),
        migrations.AlterField(
            model_name='jadwalpraktikum',
            name='waktu_mulai',
            field=models.TimeField('Waktu Mulai'),
        ),
        migrations.AlterField(
            model_name='jadwalpraktikum',
            name='waktu_selesai',
            field=models.TimeField('Waktu Selesai', blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='jadwalpraktikum',
            options={
                'ordering': ['tanggal', 'waktu_mulai', 'mata_kuliah'],
                'verbose_name': 'Jadwal Praktikum',
                'verbose_name_plural': 'Jadwal Praktikum',
            },
        ),
    ]
