# Generated by Django 4.2.23 on 2026-07-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0013_pengguna_cover_image'),
        ('pendaftaran_asleb', '0012_alter_pendaftaranasleb_metode_rekening'),
        ('ruangan', '0001_initial'),
        ('jadwal', '0005_jadwalpraktikum_ruangan_tambahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanPerubahanJadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10)),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('diajukan', 'Menunggu Persetujuan'), ('diterima', 'Disetujui'), ('ditolak', 'Ditolak')], default='diajukan', max_length=20)),
                ('catatan_laboran', models.TextField(blank=True)),
                ('diproses_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diajukan_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_perubahan_jadwal', to='pengguna.pengguna')),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permintaan_jadwal_diproses', to='pengguna.pengguna')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_perubahan', to='jadwal.jadwalpraktikum')),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pendaftaran_asleb.matakuliahasleb')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permintaan_jadwal_utama', to='ruangan.ruanganlab')),
                ('ruangan_tambahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permintaan_jadwal_tambahan', to='ruangan.ruanganlab')),
            ],
            options={
                'verbose_name': 'Permintaan Perubahan Jadwal',
                'verbose_name_plural': 'Permintaan Perubahan Jadwal',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
