# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjamanalat',
            old_name='kelas_tujuan',
            new_name='nim',
        ),
        migrations.AlterField(
            model_name='peminjamanalat',
            name='nim',
            field=models.CharField('NIM', blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='peminjamanalat',
            name='no_hp',
            field=models.CharField('No HP', blank=True, max_length=30),
        ),
    ]
