# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_rename_kelas_tujuan_add_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamanalat',
            name='status',
            field=models.CharField(
                choices=[
                    ('diajukan', 'Diajukan'),
                    ('dipinjam', 'Dipinjam'),
                    ('dikembalikan', 'Dikembalikan'),
                    ('hilang', 'Hilang'),
                    ('rusak', 'Rusak'),
                    ('digantikan', 'Digantikan'),
                ],
                default='diajukan',
                max_length=20,
            ),
        ),
    ]
