# Generated by Django 4.2.23 on 2026-06-22 07:01

from django.db import migrations, models


def isi_kode_pinjam(apps, schema_editor):
    PeminjamanAlat = apps.get_model('peminjaman', 'PeminjamanAlat')
    for peminjaman in PeminjamanAlat.objects.filter(kode_pinjam='').order_by('id'):
        peminjaman.kode_pinjam = f'PJM-{peminjaman.tanggal_pinjam:%y%m%d}-{peminjaman.id:04d}'
        peminjaman.save(update_fields=['kode_pinjam'])


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_alter_peminjamanalat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamanalat',
            name='kode_pinjam',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
        migrations.RunPython(isi_kode_pinjam, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='peminjamanalat',
            name='kode_pinjam',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
    ]
