# Generated by Django 4.2.23 on 2026-06-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0004_peminjamanalat_kode_pinjam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamanalat',
            name='jumlah',
        ),
    ]
