# Generated by Django 4.2.23 on 2026-06-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0008_paketbarang_paketbarangitem'),
        ('peminjaman', '0006_alter_peminjamanalat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamanalat',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman', to='inventaris.paketbarang'),
        ),
    ]
