# Generated by Django 4.2.23 on 2026-06-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0007_peminjamanalat_paket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pinjam', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('nama_peminjam', models.CharField(max_length=150)),
                ('nim', models.CharField(blank=True, max_length=30, verbose_name='NIM')),
                ('no_hp', models.CharField(blank=True, max_length=30, verbose_name='No HP')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaksi Peminjaman',
                'verbose_name_plural': 'Transaksi Peminjaman',
                'ordering': ['-tanggal_pinjam', '-dibuat_pada'],
            },
        ),
        migrations.AlterField(
            model_name='peminjamanalat',
            name='kode_pinjam',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='peminjamanalat',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='peminjaman.peminjamantransaksi'),
        ),
    ]
