# Generated by Django 4.2.23 on 2026-07-01 04:32

from django.db import migrations, models


def delete_rejected_peminjaman(apps, schema_editor):
    PeminjamanAlat = apps.get_model('peminjaman', 'PeminjamanAlat')
    PeminjamanTransaksi = apps.get_model('peminjaman', 'PeminjamanTransaksi')

    transaksi_ids = list(
        PeminjamanAlat.objects.filter(status='ditolak')
        .exclude(transaksi_id__isnull=True)
        .values_list('transaksi_id', flat=True)
        .distinct()
    )
    PeminjamanAlat.objects.filter(status='ditolak').delete()

    for transaksi_id in transaksi_ids:
        if not PeminjamanAlat.objects.filter(transaksi_id=transaksi_id).exists():
            PeminjamanTransaksi.objects.filter(pk=transaksi_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0009_backfill_peminjaman_transaksi'),
    ]

    operations = [
        migrations.RunPython(delete_rejected_peminjaman, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='peminjamanalat',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('dipinjam', 'Dipinjam'), ('dikembalikan', 'Dikembalikan'), ('hilang', 'Hilang'), ('rusak', 'Rusak'), ('digantikan', 'Digantikan')], default='diajukan', max_length=20),
        ),
    ]
