# Generated by Django 5.2.15 on 2026-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('lokasi', models.CharField(blank=True, max_length=150)),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
                'ordering': ['nama'],
            },
        ),
    ]
