# Generated by Django 4.2.23 on 2026-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_lokasi', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('nama_lokasi', models.CharField(max_length=150)),
                ('ukuran_lokasi', models.CharField(blank=True, max_length=100)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Lokasi',
                'ordering': ['nama_lokasi'],
            },
        ),
    ]
