# Generated by Django 4.2.23 on 2026-06-18 08:21

from django.db import migrations, models
import django.db.models.deletion


def pindahkan_lokasi_teks_ke_relasi(apps, schema_editor):
    Barang = apps.get_model('inventaris', 'Barang')
    Lokasi = apps.get_model('inventaris', 'Lokasi')

    for barang in Barang.objects.exclude(lokasi_lama='').exclude(lokasi_lama__isnull=True):
        lokasi = Lokasi.objects.filter(nama_lokasi=barang.lokasi_lama).first()
        if lokasi:
            barang.lokasi = lokasi
            barang.save(update_fields=['lokasi'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_lokasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='lokasi',
            new_name='lokasi_lama',
        ),
        migrations.AddField(
            model_name='barang',
            name='lokasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barang', to='inventaris.lokasi'),
        ),
        migrations.RunPython(pindahkan_lokasi_teks_ke_relasi, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='barang',
            name='lokasi_lama',
        ),
    ]
