# Generated by Django 5.2.15 on 2026-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_barang_kode_barang_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barang/'),
        ),
    ]
