# Generated by Codex on 2026-06-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0003_barang_foto'),
        ('inventaris', '0003_barang_lokasi_fk'),
    ]

    operations = []
