# Generated by Codex on 2026-06-21

from django.db import migrations


def update_kode_lokasi_format(apps, schema_editor):
    Lokasi = apps.get_model('inventaris', 'Lokasi')

    for lokasi in Lokasi.objects.all():
        kode_lokasi = f'LKS-{lokasi.id:04d}'
        if lokasi.kode_lokasi != kode_lokasi:
            lokasi.kode_lokasi = kode_lokasi
            lokasi.save(update_fields=['kode_lokasi'])


def restore_kode_lokasi_format(apps, schema_editor):
    Lokasi = apps.get_model('inventaris', 'Lokasi')

    for lokasi in Lokasi.objects.all():
        kode_lokasi = f'LK{lokasi.id:06d}'
        if lokasi.kode_lokasi != kode_lokasi:
            lokasi.kode_lokasi = kode_lokasi
            lokasi.save(update_fields=['kode_lokasi'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_merge_lokasi_foto_kode'),
    ]

    operations = [
        migrations.RunPython(update_kode_lokasi_format, restore_kode_lokasi_format),
    ]
