# Generated by Django 4.2.23 on 2026-06-20 18:31

from django.db import migrations, models
import django.db.models.deletion


def create_inventaris_from_barang(apps, schema_editor):
    Barang = apps.get_model('inventaris', 'Barang')
    InventarisBarang = apps.get_model('inventaris', 'InventarisBarang')

    for barang in Barang.objects.filter(inventaris__isnull=True):
        inventaris = InventarisBarang.objects.create(
            nama=barang.nama,
            kode_inventaris=barang.kode_barang,
            jumlah=barang.jumlah,
            foto=barang.foto,
            keterangan=barang.keterangan,
        )
        barang.inventaris = inventaris
        barang.save(update_fields=['inventaris'])


def remove_generated_inventaris(apps, schema_editor):
    InventarisBarang = apps.get_model('inventaris', 'InventarisBarang')
    InventarisBarang.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0005_update_kode_lokasi_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kode_inventaris', models.CharField(blank=True, max_length=50, unique=True)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='barang/')),
                ('keterangan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventaris Barang',
                'verbose_name_plural': 'Inventaris Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='inventaris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_barang', to='inventaris.inventarisbarang'),
        ),
        migrations.RunPython(create_inventaris_from_barang, remove_generated_inventaris),
    ]
