# Generated by Django 4.2.23 on 2026-06-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0007_update_kode_barang_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_paket', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('keterangan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket Barang',
                'verbose_name_plural': 'Paket Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PaketBarangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('inventaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_items', to='inventaris.inventarisbarang')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventaris.paketbarang')),
            ],
            options={
                'verbose_name': 'Item Paket Barang',
                'verbose_name_plural': 'Item Paket Barang',
                'ordering': ['inventaris__nama'],
                'unique_together': {('paket', 'inventaris')},
            },
        ),
    ]
