# Generated by Django 4.2.23 on 2026-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangTertinggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang_tertinggal', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('nama_barang', models.CharField(max_length=150)),
                ('jenis_barang', models.CharField(max_length=100)),
                ('jumlah_barang', models.PositiveIntegerField(default=1)),
                ('tanggal_ditemukan', models.DateField()),
                ('tanggal_diambil', models.DateField(blank=True, null=True)),
                ('nama_pemilik', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('tertinggal', 'Tertinggal'), ('diajukan', 'Diajukan'), ('diambil', 'Diambil'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='tertinggal', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barang Tertinggal',
                'verbose_name_plural': 'Barang Tertinggal',
                'ordering': ['-tanggal_ditemukan', '-dibuat_pada'],
            },
        ),
    ]
