# Generated by Django 4.2.23 on 2026-06-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang_tertinggal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangtertinggal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barang_tertinggal/'),
        ),
    ]
