# Generated by Django 4.2.23 on 2026-07-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0015_school_pengalaman_pendidikan_fields'),
        ('barang_tertinggal', '0003_sederhanakan_status_barang_tertinggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangtertinggal',
            name='nim_pemilik',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='NIM Pemilik'),
        ),
        migrations.AddField(
            model_name='barangtertinggal',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barang_tertinggal', to='pengguna.pengguna'),
        ),
    ]
