name: Test AlmaLinux Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Tampilkan informasi server
        run: |
          echo "Runner berhasil dijalankan"
          echo "User: $(whoami)"
          echo "Folder: $(pwd)"
          echo "Hostname: $(hostname)"
          python3 --version
